### ISSUE TITLE
Support for 0.12 HCL

### ISSUE THREAD

**Issue by ahelal** [xchapter7x/clarity#1]
Hi,

Thank you very much for the project. Any intention to support HCL2 ?

Cheers.

**Comment by xchapter7x** [comment]
Hey @ahelal ,

Glad you found value in this project. I've been debating if I should continue work on `clarity` or shift focus to [conftest](https://github.com/instrumenta/conftest) which is another project i'm a maintainer of, which also supports the ability to test hcl/hcl2.

I'd be curious on your thoughts on where the most value is moving forward. 

Thanks in advance for your thoughts. :)

**Comment by ahelal** [comment]
Hi @xchapter7x 

Thank you for pointing out conftest, I will have a look first. Initially it might just be okay to use it :)

Cheers,

**Comment by aheumaier** [comment]
Hi @xchapter7x , 

Openening this topic again since I it seems to provide  a great value for my work.
I there any intention to provide HCL2/ TF >=0.12.x support?

I would offer help to provide help on longer maintenance. 

Cheers,

**Comment by xchapter7x** [comment]
Hi @aheumaier , 

im glad to hear this is adding value to your work. 

I've reopened the issued and ill look into adding hcl2 support shortly. 

In the meantime, I'd be really interested in hearing about your experience and use case. If you wouldnt mind taking some time to share that would be greatly appreciated. Thanks :)

-John

**Comment by aheumaier** [comment]
For a large automotive customer project  TF 0.12 on Azure is set.
Since this is TDD I am looking at the landscape for frameworks testing cleanly this setups besides the ~~ugly~~ limited terratest .

Your policy based approach  with Cucumber based BDD seems close to what I am looking for

**Comment by xchapter7x** [comment]
thanks for the context.

I was exploring incorporating hcl2, and im thinking ill do this in a few PRs. 
It seems ill need to migrate to using go modules to leverage the hcl v2 packages. 

then ill incorporate the support for hcl2. 

happy to accept any PRs you might have for this issue or any other features you might find valuable. 

Ill start the modules migration today and update this issue as it goes.

**Comment by aheumaier** [comment]
Like moving to go.mod

A quick look seems to boilsdown to replace [hcl.Unmashall](https://github.com/xchapter7x/clarity/blob/7bf9d81d07d74d7b5959459c63e6e13d4ade457c/pkg/matchers/terraform.go#L201) with is removed in hcl2/hcl and replaced by several [other options](https://github.com/hashicorp/hcl2/issues/42)

One [issure coming back over and over in several tool is the lack of var expansion support ](https://github.com/instrumenta/conftest/issues/221)) in TF tooling. 
I agree on the point that this is implemented in TF already  - but haven't found a solid solution so far that actually resolves this issue in other tools.

**Comment by xchapter7x** [comment]
> One [issure coming back over and over in several tool is the lack of var expansion support ](https://github.com/instrumenta/conftest/issues/221)) in TF tooling.
> I agree on the point that this is implemented in TF already - but haven't found a solid solution so far that actually resolves this issue in other tools.

I've been kicking around an idea for an approach to address the problem set where ENV Var expansion would seem most valuable. ill keep dropping my thoughts here: https://github.com/xchapter7x/clarity/issues/4

**Comment by xchapter7x** [comment]
@aheumaier 
Check out the latest RC:
https://github.com/xchapter7x/clarity/releases/tag/v0.6.2-rc.11

I don't know your use case, but there is now support for hcl2. 
Let me know if it works for you.

If not, please provide a sample hcl which shows the functionality that is not compatible.

Thanks in for your involvement :)

**Comment by xchapter7x** [comment]
https://github.com/xchapter7x/clarity/releases/tag/v0.7.0
now comes with support for hcl2 by swapping the given from `Terraform` to `HCL2`
