### ISSUE TITLE
HCL check does not support terraform v0.12 syntax 

### ISSUE THREAD

**Issue by fengyebxh** [xchapter7x/clarity#12]
**Describe the bug**
I define the following variable in my terraform template,
```
variable "storageName" {
  description = "datastore names that will be used for creating disks"
  type        = list
}
```
when run clarity testing, it is failed with the following error message

```
 Given Terraform                                    # terraform.go:92 -> *Match
    hcl Unmarshal failed: At 164:17: Unknown token: 164:17 IDENT list
    And a "vsphere" of type "provider"                 # terraform.go:279 -> *Match
    Then attribute "version" equals "1.13"             # terraform.go:409 -> *Match
```

**To Reproduce**
Using clarity v7.0
1. define variable with type = list
2. run clarity test

**Expected behavior**
definition of "type = list" is supported in terraform 0.12, HCL check should not be failed

**Comment by xchapter7x** [comment]
Hi @fengyebxh 

Thanks for reporting this issue.
Let me try to reproduce this locally and see what i find. stay tuned :)

**Comment by xchapter7x** [comment]
In the meantime have you tried switching in your feature file gherkin
```
Given Terraform
```
replace with
```
Given HCL2
```

this will switch the parser to a .12 compatible version
