### ISSUE TITLE
Typo in the project description

### ISSUE THREAD

**Issue by Nklya** [xchapter7x/clarity#2]
Hello.

I've found a typo in the project description.
```
A declaritive test framewark for Terraform: For more complete testing support using OPA policies check out: https://github.com/instrumenta/conftest
```

should be `A declarative test framework ...`

P.S. thanks for the project, looks interesting.

**Comment by xchapter7x** [comment]
fixed.

Thanks for the correction :)

curious if/how you're using clarity?

**Comment by Nklya** [comment]
Thanks. You're welcome 😊 
No, I'm not using clarity. Just found it recently)
