### ISSUE TITLE
Error: hcl Unmarshal failed:  Missing newline after block definition

### ISSUE THREAD

**Issue by efernandes-dev-ops** [xchapter7x/clarity#23]
**Describe the bug**
I get the following error when I try to run my clarity test.

```--- Failed steps:

  Scenario: we allow iam users access to view billing # account.feature:3
    Given HCL2 # account.feature:4
      Error: hcl Unmarshal failed: parse hcl2 config: 
 [:50,2-10: Missing newline after block definition; A block definition must end with a newline. 
]
```

The following below are the files I've got in my module:

variables.tf file

```
variable "name" {
  description = "Account name prefix"
  type            = string
}

variable "account" {
  description = "The account type being created (prod, nonprod, tools, sandbox)"
  type            = string
}

variable "parent" {
  description = "The ID of the parent - Root account or OU"
  type            = string
}

variable "ou" {
  description = "The name of the OU - used to create email address"
  type            = string
}

variable "email_prefix" {
  description = "Email to attach to this account"
  type            = string
}

variable "email_domain" {
  description = "Email domain"
  type            = string
}

variable "role_name" {
  description = "Name of the role that will be automatically trusted from the master account"
  type            = string
}

variable "tags" {
  default = []
}

variable "name" {
   description = "Name for account"
   type = string
}

variable "email {
   description = "Email for account"
   type = string
}
```

account.tf file

```
resource "aws_organizations_account" "ou_account" {
     name                       = var.name
     email                       = var.email
     parent_id                = var.parent
     iam_user_access_to_billing = "ALLOW"
     role_name              = var.role_name
     tags                        = var.tags
}
```

account.feature file

```
Feature: We should have an aws account and as such we should configure the account correctly

  Scenario: we allow iam users access to view billing
    Given HCL2
    And a "aws_organizations_account" of type "resource"
    Then attribute "iam_user_access_to_billing" equals "ALLOW"
```

**To Reproduce**
1. Add the above files
2. Run clarity
3. See error

**Expected behaviour**
The test passes after running clarity account.feature.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: osX
 - Clarity Version: v7.0
 - Terraform Version:  v0.14.0 

**Additional context**

I don't believe I am missing a newline, I can confirm I have got a newline at the end of the aws block resource. I have also run terraform fmt to make sure I have not got any formatting issues with the code and that's returned successfully.

**Comment by efernandes-dev-ops** [comment]
Sorry about the formatting don't know what happened there. Let me know if you need any more info @xchapter7x . 
Thanks

**Comment by xchapter7x** [comment]
@efernandes-dev-ops thanks for reporting this. 

Im not sure if its an issue with your copy/paste, but one of the blocks is missing a `"`

```

variable "email {
   description = "Email for account"
   type = string
}
```

That could be causing the hcl2 parser to error out. 

let me know if that fixes it or if i should dig a little more

**Comment by efernandes-dev-ops** [comment]
@xchapter7x Oh unfortunately that's an issue with my copy and paste. I typed it in manually when creating the github issue as I had the variables in a locals.tf file and just thought it would be easier to recreate the issue if put everything in the vars file

**Comment by xchapter7x** [comment]
with these 3 files: https://gist.github.com/xchapter7x/5b0d0f6a553a5870303e814a040a5db8

i get the following output:

```
-> % ./clarity account.feature
Feature: We should have an aws account and as such we should configure the account correctly

  Scenario: we allow iam users access to view billing          # account.feature:3
    Given HCL2                                                 # terraform.go:102 -> *Match
    And a "aws_organizations_account" of type "resource"       # terraform.go:279 -> *Match
    Then attribute "iam_user_access_to_billing" equals "ALLOW" # terraform.go:409 -> *Match

1 scenarios (1 passed)
3 steps (3 passed)
1.876033ms
```

this is using the latest 0.7.0 on OSX. 

If you want to upload your actual files to a gist or something, i can take a look, but i cant reproduce your issue with what you pasted (fixing the missing `"`)

**Comment by efernandes-dev-ops** [comment]
Can you confirm that you are on Terraform v0.14.0? 

Going to see what's different with my setup...

**Comment by xchapter7x** [comment]
Clarity doesn't use terraform. It bundles in the hcl2 packages, which are
also used in terraform.

**Comment by efernandes-dev-ops** [comment]
So I narrowed down the issue on why it's failing on my side, so we name our variables.tf file as _vars.tf. The reason for this is because we wanted to make easier for terraform newbies in our company to understand that if they wanted to figure out which files were responsible for configuration of the module. It seems that if you an _ at the start of the variables.tf file it throws the above error. What I did find interesting though is if I remove the file completely and don't declare any variables the test still passes but I guess that's because the test isn't really testing that variables are declared etc

**Comment by efernandes-dev-ops** [comment]
But then if it passes without the file why would it fail with the underscore (_) in front of it ? I am wondering if you can reproduce it on your side

**Comment by xchapter7x** [comment]
Does it pass if you keep the file, but rename it without the underscore? That would prove if the underscore has anything to do with it. Otherwise it seems like its just the contents of the file.

On my end no matter what I name the variables file, it still works. If you want to send your actual files somehow, that might help me in reproducing what you're seeing.

**Comment by efernandes-dev-ops** [comment]
So I think I narrowed it down further, it passes if I keep the file and rename it without the underscore. However upon checking the contents of the file I noticed it didn't have a newline at the end, once I added the newline it passed with the file being _vars.tf.

I have attached the file here for you to re-produce.

[_vars.txt](https://github.com/xchapter7x/clarity/files/5678187/_vars.txt)

**Comment by xchapter7x** [comment]
I believe i know what the issue is. 
Clarity concatenates the .tf files before it unmarshals them. if there isn't a newline at the end of one of the files, then the formatting becomes invalid for the hcl unmarshaller. 

ill push up a test to prove the issue and a fix shortly.

**Comment by xchapter7x** [comment]
@efernandes-dev-ops 
latest version: https://github.com/xchapter7x/clarity/releases/tag/v0.7.1

should fix your newline issue, without needing to remove the newline. 


thanks for reporting the issue.

Glad you're finding value in the tool. Feel free to ping with feedback / contributions / suggestions, etc.

:)

**Comment by efernandes-dev-ops** [comment]
Awesome, thanks for the fix. Yeah definitely feel there is a place for clarity, at the moment I want to try and bring it in and get other people in my org to use it. I also opened a PR to add it here https://github.com/shuaibiyy/awesome-terraform/pull/108. Hopefully once that get's merged in a few more people will stumble here :)
