### ISSUE TITLE
Clarity testing for checking resource tags

### ISSUE THREAD

**Issue by goodwinsagar** [xchapter7x/clarity#7]
Hi,

I am new to clarity test tool. I wanted to know whether clarity can be used to check whether tags are added to AWS resources or not.

Any suggestions here would be helpful.

Regards,
Reena

**Comment by xchapter7x** [comment]
Hi @goodwinsagar ,

Thanks for reaching out.

Yes, you can check for the existence of tags.

For something like this:
```hcl
resource "aws_instance" "web" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags = {
    Name = "HelloWorld"
  }
}
```

one could craft a gherkin like this:

```gherkins
Given HCL2
When a "aws_instance" of type "resource"
Then attribute "tags" exists
```

you could also check for equality or regex to make sure particular tags are added
