### ISSUE TITLE
Custom Rules to test against Terraform templates

### ISSUE THREAD

**Issue by TechGirl-3** [xchapter7x/clarity#8]
Hi,

Is it possible write to custom rules to test Terraform files. 

Regards,
TechGirl-3

**Comment by xchapter7x** [comment]
Hi @TechGirl-3 ,

Thanks for reaching out.

By custom rules, im guessing you mean you'd like to write your own gherkins that are not currently in the list of supported matchers?

Clarity is really a purpose built extension on top of https://github.com/cucumber/godog . What this allows us to do is to author our own gherkins, and using the clarity cli (indirectly the godog cli) compile a new binary which includes any new matchers you might desire. 

You could also fork the repo, add any new gherkins you'd like, and contribute them back in the form of a PR. I'd be happy to accept them :)

-John
